### ISSUE TITLE
Pretty symbols display almost invisible if followed by a space

### ISSUE THREAD

**Issue by pseudohuman92** [coq-community/vsc-conceal#9]
If there is no trailing space, newline is fine, they are displayed white (I am using a dark theme.). If there is a trailing space, they are displayed grey that is almost invisible. You can see examples of both behaviors below.

![prett-example-bug](https://user-images.githubusercontent.com/25036316/112186960-018ac300-8bd8-11eb-8d83-d813b5ebe774.png)

**Comment by cht33** [comment]
i have the same problem! could anyone give some tips?

**Comment by thiago4455** [comment]
The temporary solution is to change the setting "editor.renderWhitespace" to "trailing" or "none".

The color issue is caused by the opaque dots around the pretty symbol.
